version: "3.9"

services:
  fastapi_app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: ravprojectdev/rag:latest
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

